### ISSUE TITLE
Compile error for nodemcu esp8266 12e

### ISSUE THREAD

**Issue by Sourav2paul** [adafruit/DHT-sensor-library#104]
I'm a beginner on arduino board projects.I'm doing a project of home automation using NODEMCU ESP8266 12E and blynk.when I'm trying t compile it its showing an error massege and showing:-

Arduino: 1.8.5 (Windows Store 1.8.10.0) (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

Build options changed, rebuilding all
exit status -1073741515
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

MY CODE IS:-

/*************************************************************
  Download latest Blynk library here:
    https://github.com/blynkkk/blynk-library/releases/latest

  Blynk is a platform with iOS and Android apps to control
  Arduino, Raspberry Pi and the likes over the Internet.
  You can easily build graphic interfaces for all your
  projects by simply dragging and dropping widgets.

    Downloads, docs, tutorials: http://www.blynk.cc
    Sketch generator:           http://examples.blynk.cc
    Blynk community:            http://community.blynk.cc
    Follow us:                  http://www.fb.com/blynkapp
                                http://twitter.com/blynk_app

  Blynk library is licensed under MIT license
  This example code is in public domain.

 *************************************************************
  This example runs directly on ESP8266 chip.

  Note: This requires ESP8266 support package:
    https://github.com/esp8266/Arduino

  Please be sure to select the right ESP8266 module
  in the Tools -> Board menu!

  Change WiFi ssid, pass, and Blynk auth token to run :)
  Feel free to apply it to any other example. It's simple!
 *************************************************************/

/* Comment this out to disable prints and save space */
#define BLYNK_PRINT Serial

#include <ESP8266WiFi.h>
#include <BlynkSimpleEsp8266.h>

// You should get Auth Token in the Blynk App.
// Go to the Project Settings (nut icon).
char auth[] = "authcode";

// Your WiFi credentials.
// Set password to "" for open networks.
char ssid[] = "Xiaomi_712F";
char pass[] = "bolajabena";

void setup()
{
  // Debug console
  Serial.begin(9600);

  Blynk.begin(auth, ssid, pass);
}

void loop()
{
  Blynk.run();
}

**Comment by geofbaum** [comment]
@Sourav2paul Can I ask why you are posting this issue here? Are you trying to use the Blynk library with a DHT sensor?

Secondly are you sure that you have installed all of the libraries needed correctly and can you please enable the verbose output during compilation? I ask as it might help point to a specific issue with the error.
