### ISSUE TITLE
Raspberry Pi WProgram.h error

### ISSUE THREAD

**Issue by tomforsyth90** [adafruit/DHT-sensor-library#105]
Trying to get the sensor to work with wiringPi but keep getting an error. Originally it was DHT.h was missing.. downloaded that and added it to the file and now its saying its missing WProgram.h
How can i fix this?

**Comment by geofbaum** [comment]
@tomforsyth90 You might want to use this library instead of this one, https://github.com/adafruit/Adafruit_Python_DHT, as this one is geared mainly toward usage by an Arduino  type board.

**Comment by PaintYourDragon** [comment]
Recommend using CircuitPython for Pi usage. Command to install is:
`pip3 install adafruit_circuitpython_dht`
Usage examples here:
https://learn.adafruit.com/dht/dht-circuitpython-code
