### ISSUE TITLE
3 out of 4 values are 0 on DT11 with force option

### ISSUE THREAD

**Issue by nablabla** [adafruit/DHT-sensor-library#117]
Hi,

I think the title says it. Tried both: using external 5V and using USB to power both, the sensor and the Arduino Nano.
This is my output

Temp: 22
Humidity: 51
Temp: 0
Humidity: 0
Temp: 0
Humidity: 0
Temp: 0
Humidity: 0
Temp: 22
Humidity: 51
Temp: 0
Humidity: 0
Temp: 0
Humidity: 0
Temp: 0
Humidity: 0
...

repeating itself exactly that way

I think none of the issues here are similar

void loop() {
  currentTemperature = dht.readTemperature(true); // got rid of non-metric (S)cale
  Serial.print("Temp: ");
  Serial.println(currentTemperature);
  delay(5000);
  currentHumidity = dht.readHumidity(true);
  Serial.print("Humidity: ");
  Serial.println(currentHumidity);
  delay(5000);
}

Thank you very much

**Comment by PaintYourDragon** [comment]
Try 1.3.1 release. Several pull requests were merged, including some related to timing and pin behavior. Seems to be working consistently with DHT11 & force.
