### ISSUE TITLE
Add ArduBadge Badge (Installation Guide)

### ISSUE THREAD

**Issue by gilmaimon** [adafruit/DHT-sensor-library#119]
Hi!
A nice addition to the readme file can be this [ArduBadge](https://www.ardu-badge.com/) Badge:
[![arduino-library-badge](https://www.ardu-badge.com/badge/DHT%20sensor%20library.svg)](https://www.ardu-badge.com/DHT%20sensor%20library)
Code:
`[![arduino-library-badge](https://www.ardu-badge.com/badge/DHT%20sensor%20library.svg)](https://www.ardu-badge.com/DHT%20sensor%20library)`

It shows:
1. That the library is on the arduino IDE (via the Library Manager)
2. The latest version (1.3.1)
3. Clicking on the badge redirects to a custom installation guide for "DHT sensor library" that shows how to install it via the Library Manager and using a ZIP file. Can be very helpfull for new users!

Thank You.

**Comment by ladyada** [comment]
hiya this doesn't show dependancies, so it will cause more support issues - we already have a gudie here :) https://learn.adafruit.com/dht
