### ISSUE TITLE
Library 1.3.2 causes NAN (checksum failures): likely cause and  proposed fix

### ISSUE THREAD

**Issue by JmBelisle** [adafruit/DHT-sensor-library#124]
**_Summary_**
The code of V1.3.2 occasionnally misses the first LOW DHT signal of the 80us LOW/80us HIGH signal pair that preceeds the 40 bit information data stream.  This is likely because occasionnally, the DHT takes more that 40us (line 174) to pull the line down and thus the DHT.cpp code expecting a LOW (line 182) but reading the trailing edge of the priorly ESP generated HIGH (line 187), gets out of sync with the bit stream and interprets the trailing edge as the HIGH signal of the 80us/80us pair. When the DHT finally sends the 80usLOW/80usHIGH pair, the code incorrectly interprets it as the first data bit, thus adding a bit and throwing the ESP computed checksum out of balance with the DHT computed checksum.

**_The fix (tested on ESP8266 NodeMCU)_**
Increase the wait time before reception of the 80usLOW/80usHIGH start signal from the DHT from 40us to 50us (minimum) at line 174 in DHT.cpp.

**_Supporting evidence_** 
Using V1.3.2 of the library with NodeMCU ESP8266 and Adafruit DHT22 modules.
I got 4%-8% of calls returning NAN. By going to debug mode (#define DHT_DEBUG) in dht.cpp I found that ALL errors were of type "DHT checksum failure" such as below (_Italics_ : my program; **Bold** produced by dht debug mode) :
      _JMB : Read# 000087_
      **Received from DHT:              
      80, C0, 80, 67, 28 =? 27
      DHT checksum failure!**
      _JMB : Read# 000088_
      **Received from DHT:
      1, 81, 0, CE, 50 =? 50**
Looking at the 40 bit pattern of the bytes received in these 2 consecutive calls (3 seconds apart), I realized they were the same but shifted by one bit: The correct call bit pattern was the same as the Checksum failure one but shifted one bit left. As below:
**80,C0,80,67,28** == 10000000,11000000,10000000,01100111,00101000
**01,81,00,CE,50** == 00000001,10000001,00000000,11001110,01010000

From these observations, I surmised that the DHT22 had transmitted the right information in both cases but that somehow a leading "additional bit" had been read ahead of the correct binary sequence thus explaining the shift. Not having a scope to look at the bit stream in realtime, I modified the DHT.cpp library to :
1. capture the (duration) of the two LOW and HIGH level data pin signals (from the DHT22) that preceed the 40 bit data stream (measured in lines 182 and 187 of DHT.cpp). 
2. print the duration of the 80 LOW and HIGH level data content that provide the 40 bits of data (captured in array "cycles" in lines 202 and 203).  The output became : 

Received from DHT:
80, C0, 80, 67, 28 =? 27
DHT checksum failure!
**000 009**   -->correspond to 80usLOW/80usHIGH start signal pair from DHT
**118**   80  83  82  83  83  82  83  83 103   82  83 ... -->LOW signal of bit signal pair 
**123**   39  40  40  39  40  40  39 113 115  40  39 ... -->HIGH signal of bit signal pair
    1     0    0    0    0    0    0    0     1     1    0    0 ... -->Resulting bit
Received from DHT:
01, 81, 00, CE, 50 =? 50
**090 121**
  75   79   83   83   83   83   83   83 103   83  83 ... LOW signal of bit signal pair
  40   40   39   39   40   39   39 113 115   39  39 ... HIGH signal of bit signal pair
    0     0     0     0     0     0     0     1     1     0    0 ... Resulting bit

One reads/interprets the info as follows:
**000** is the calculated duration (by DHT.cpp) of the 80usLOW part of the start signal pair
**009** is the calculated duration (by DHT.cpp) of the 80usHIGH part of the start signal pair
**118** is the calculated duration (by DHT.cpp) of the LOW part of the LOW/HIGH signal for the first bit 
**123** is the calculated duration (by DHT.cpp) of the HIGHpart of the LOW/HIGH signal for the first bit 
       (and given that 123 > 118) that bit is a "1".)
Note that from the read that did not generate a checksum error we see:
**090** is the calculated duration (by DHT.cpp) of the 80usLOW part of the start signal pair
**121** is the calculated duration (by DHT.cpp) of the 80usHIGH part of the start signal pair
Also note that 90us and 121us are larger than the 80us spec.... but this information is NOT generated from a scope so it's accuracy is not total.  Suffice it to say 121 is still 50% larger than 80 and thus specs are not quite met.

Likely explanation: say the DHT pulled the line low 49us (and not 40us) after ESP relinquishes control after going to input mode; then after a 40us delay (line 174)  when the ESP expects the LOW part of the start pair, the line is still HIGH from the ESP command at line 171.  The code thus registers a zero LOW duration (because the line is HIGH, not low).  The duration of the HIGH portion is 9us, which corresponds to difference in time between the 40us wait on part of the ESP and the 49us of actual time the DHT took to take the line down.  The DHT.cpp code then begins the information bit read loop (line 201) and mistakes the now incoming start signal LOW/HIGH pair as the first bit... thus adding a bit and shifting the bit stream as we observe in the printed Debug data..

**_Conclusion_**
The fix is simply to increase the 40us delay to 50us, assuming that the 9us delay for the DHT in starting the LOW/HIGH start signal is the maximum time the DHT will ever go over the 40us spec (no certainty here). 
 I did that modification and ran 10000 successive reads on each of 3 DHT sensors from ADAFRUIT and got ZERO errors over those 30000 reads.  I ran the same tests with a delay of 55us and got the same results of ZERO errors. 

I agree that lacking scope and a larger sample set of sensors, the 55us is a better choice of delay. 
 I also agree that because these errors are timing related, that the fix may not work for other platforms since I have not performed such tests.  I intend to forward my proposed changes in both the debug capture and printouts, and the timing delay increase through a pull request.

jmb

**Comment by ladyada** [comment]
hiya thanks - lets keep the discussion at 
https://github.com/adafruit/DHT-sensor-library/issues/116
:)
