### ISSUE TITLE
Slow & Incorrect readings starting from 1.3.3 (timing?)

### ISSUE THREAD

**Issue by mohsh86** [adafruit/DHT-sensor-library#137]
As the subject suggests, got 2 different NodeMCU boards from different suppliers.
Tested DH11, DH22 & DH21 (AOSONG2301).

Data on D4, tried both 5v and 3.3, running on Arduino 1.8.9

staring from Lib 1.3.3 Readings are:

Temperature: 11.60C
Humidity: 3310.30%
Heat index: -89931.09C

would occasionally read correct values.

1.3.2 and earlier (correct values)

Temperature: 23.10C
Humidity: 65.20%
Heat index: 23.21C

I initially thought it's  faulty sensor, but reverting back to older lib version fixed the issue.

**Comment by ladyada** [comment]
dup issue https://github.com/adafruit/DHT-sensor-library/issues/116
