### ISSUE TITLE
Allow library to be used without the unified driver thing

### ISSUE THREAD

**Issue by cr1st1p** [adafruit/DHT-sensor-library#140]
- Arduino board: Lolin nodemcuv3 esp8266

- Arduino IDE version: eclipse; code compiled and libraries retreived via 'platformio'

I'm using this code as library number 19 on platformio.
I do not use the 'unified version', but only DHT.h/cpp.
Unfortunately compiler is asked to also compile dht_u.cpp which requires the unified driver library (library 31 on platformio) which forces me to add the library as a dependency of the project even though I do not use it. 

Could you maybe surround both dht_u.h and dht_u.cpp with something like
#ifndef DHT_WITHOUT_UNIFIED_DRIVER ?
And probably the README file should as well be changed a bit to not say, in bold, that library is needed, and talk about the new define.

Thank you!

**Comment by ladyada** [comment]
wontfix - please use the library as is!
