### ISSUE TITLE
arduino error in compling board

### ISSUE THREAD

**Issue by atulgaur10** [adafruit/DHT-sensor-library#141]
Arduino: 1.8.9 (Windows 10), Board: "Arduino Pro or Pro Mini, ATmega328P (5V, 16 MHz)"

C:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -hardware C:\Users\atulg\AppData\Local\Arduino15\packages -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -tools C:\Users\atulg\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\atulg\OneDrive\Documents\Arduino\libraries -fqbn=arduino:avr:pro:cpu=16MHzatmega328 -ide-version=10809 -build-path C:\Users\atulg\AppData\Local\Temp\arduino_build_489488 -warnings=none -build-cache C:\Users\atulg\AppData\Local\Temp\arduino_cache_994996 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avrdude.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.avrdude-6.3.0-arduino14.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.arduinoOTA.path=C:\Users\atulg\AppData\Local\Arduino15\packages\arduino\tools\arduinoOTA\1.2.1 -prefs=runtime.tools.arduinoOTA-1.2.1.path=C:\Users\atulg\AppData\Local\Arduino15\packages\arduino\tools\arduinoOTA\1.2.1 -prefs=runtime.tools.avr-gcc.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.avr-gcc-5.4.0-atmel3.6.1-arduino2.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -verbose C:\Users\atulg\Desktop\Project\sketch_aug28a\sketch_aug28a.ino
C:\Program Files (x86)\Arduino\arduino-builder -compile -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -hardware C:\Users\atulg\AppData\Local\Arduino15\packages -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -tools C:\Users\atulg\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\atulg\OneDrive\Documents\Arduino\libraries -fqbn=arduino:avr:pro:cpu=16MHzatmega328 -ide-version=10809 -build-path C:\Users\atulg\AppData\Local\Temp\arduino_build_489488 -warnings=none -build-cache C:\Users\atulg\AppData\Local\Temp\arduino_cache_994996 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avrdude.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.avrdude-6.3.0-arduino14.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.arduinoOTA.path=C:\Users\atulg\AppData\Local\Arduino15\packages\arduino\tools\arduinoOTA\1.2.1 -prefs=runtime.tools.arduinoOTA-1.2.1.path=C:\Users\atulg\AppData\Local\Arduino15\packages\arduino\tools\arduinoOTA\1.2.1 -prefs=runtime.tools.avr-gcc.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.avr-gcc-5.4.0-atmel3.6.1-arduino2.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -verbose C:\Users\atulg\Desktop\Project\sketch_aug28a\sketch_aug28a.ino
Using board 'pro' from platform in folder: C:\Program Files (x86)\Arduino\hardware\arduino\avr
Using core 'arduino' from platform in folder: C:\Program Files (x86)\Arduino\hardware\arduino\avr
Build options changed, rebuilding all
Detecting libraries used...
"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10809 -DARDUINO_AVR_PRO -DARDUINO_ARCH_AVR "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "C:\\Users\\atulg\\AppData\\Local\\Temp\\arduino_build_489488\\sketch\\sketch_aug28a.ino.cpp" -o nul
"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10809 -DARDUINO_AVR_PRO -DARDUINO_ARCH_AVR "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "-IC:\\Program Files (x86)\\Arduino\\libraries\\LiquidCrystal\\src" "C:\\Users\\atulg\\AppData\\Local\\Temp\\arduino_build_489488\\sketch\\sketch_aug28a.ino.cpp" -o nul
"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10809 -DARDUINO_AVR_PRO -DARDUINO_ARCH_AVR "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "-IC:\\Program Files (x86)\\Arduino\\libraries\\LiquidCrystal\\src" "-IC:\\Users\\atulg\\OneDrive\\Documents\\Arduino\\libraries\\DHT_sensor_library" "C:\\Users\\atulg\\AppData\\Local\\Temp\\arduino_build_489488\\sketch\\sketch_aug28a.ino.cpp" -o nul
"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10809 -DARDUINO_AVR_PRO -DARDUINO_ARCH_AVR "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "-IC:\\Program Files (x86)\\Arduino\\libraries\\LiquidCrystal\\src" "-IC:\\Users\\atulg\\OneDrive\\Documents\\Arduino\\libraries\\DHT_sensor_library" "C:\\Program Files (x86)\\Arduino\\libraries\\LiquidCrystal\\src\\LiquidCrystal.cpp" -o nul
"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10809 -DARDUINO_AVR_PRO -DARDUINO_ARCH_AVR "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "-IC:\\Program Files (x86)\\Arduino\\libraries\\LiquidCrystal\\src" "-IC:\\Users\\atulg\\OneDrive\\Documents\\Arduino\\libraries\\DHT_sensor_library" "C:\\Users\\atulg\\OneDrive\\Documents\\Arduino\\libraries\\DHT_sensor_library\\DHT.cpp" -o nul
"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10809 -DARDUINO_AVR_PRO -DARDUINO_ARCH_AVR "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "-IC:\\Program Files (x86)\\Arduino\\libraries\\LiquidCrystal\\src" "-IC:\\Users\\atulg\\OneDrive\\Documents\\Arduino\\libraries\\DHT_sensor_library" "C:\\Users\\atulg\\OneDrive\\Documents\\Arduino\\libraries\\DHT_sensor_library\\DHT_U.cpp" -o nul
"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10809 -DARDUINO_AVR_PRO -DARDUINO_ARCH_AVR "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "-IC:\\Program Files (x86)\\Arduino\\libraries\\LiquidCrystal\\src" "-IC:\\Users\\atulg\\OneDrive\\Documents\\Arduino\\libraries\\DHT_sensor_library" "-IC:\\Users\\atulg\\OneDrive\\Documents\\Arduino\\libraries\\Adafruit_Sensor-master" "C:\\Users\\atulg\\OneDrive\\Documents\\Arduino\\libraries\\DHT_sensor_library\\DHT_U.cpp" -o nul
Generating function prototypes...
"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10809 -DARDUINO_AVR_PRO -DARDUINO_ARCH_AVR "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "-IC:\\Program Files (x86)\\Arduino\\libraries\\LiquidCrystal\\src" "-IC:\\Users\\atulg\\OneDrive\\Documents\\Arduino\\libraries\\DHT_sensor_library" "-IC:\\Users\\atulg\\OneDrive\\Documents\\Arduino\\libraries\\Adafruit_Sensor-master" "C:\\Users\\atulg\\AppData\\Local\\Temp\\arduino_build_489488\\sketch\\sketch_aug28a.ino.cpp" -o "C:\\Users\\atulg\\AppData\\Local\\Temp\\arduino_build_489488\\preproc\\ctags_target_for_gcc_minus_e.cpp"
"C:\\Program Files (x86)\\Arduino\\tools-builder\\ctags\\5.8-arduino11/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\\Users\\atulg\\AppData\\Local\\Temp\\arduino_build_489488\\preproc\\ctags_target_for_gcc_minus_e.cpp"
Compiling sketch...
"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10809 -DARDUINO_AVR_PRO -DARDUINO_ARCH_AVR "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "-IC:\\Program Files (x86)\\Arduino\\libraries\\LiquidCrystal\\src" "-IC:\\Users\\atulg\\OneDrive\\Documents\\Arduino\\libraries\\DHT_sensor_library" "-IC:\\Users\\atulg\\OneDrive\\Documents\\Arduino\\libraries\\Adafruit_Sensor-master" "C:\\Users\\atulg\\AppData\\Local\\Temp\\arduino_build_489488\\sketch\\sketch_aug28a.ino.cpp" -o "C:\\Users\\atulg\\AppData\\Local\\Temp\\arduino_build_489488\\sketch\\sketch_aug28a.ino.cpp.o"
sketch_aug28a:10:5: error: no matching function for call to 'DHT::DHT()'

 DHT dht;

     ^

In file included from C:\Users\atulg\Desktop\Project\sketch_aug28a\sketch_aug28a.ino:4:0:

C:\Users\atulg\OneDrive\Documents\Arduino\libraries\DHT_sensor_library/DHT.h:49:4: note: candidate: DHT::DHT(uint8_t, uint8_t, uint8_t)

    DHT(uint8_t pin, uint8_t type, uint8_t count=6);

    ^

C:\Users\atulg\OneDrive\Documents\Arduino\libraries\DHT_sensor_library/DHT.h:49:4: note:   candidate expects 3 arguments, 0 provided

C:\Users\atulg\OneDrive\Documents\Arduino\libraries\DHT_sensor_library/DHT.h:47:7: note: candidate: constexpr DHT::DHT(const DHT&)

 class DHT {

       ^

C:\Users\atulg\OneDrive\Documents\Arduino\libraries\DHT_sensor_library/DHT.h:47:7: note:   candidate expects 1 argument, 0 provided

C:\Users\atulg\OneDrive\Documents\Arduino\libraries\DHT_sensor_library/DHT.h:47:7: note: candidate: constexpr DHT::DHT(DHT&&)

C:\Users\atulg\OneDrive\Documents\Arduino\libraries\DHT_sensor_library/DHT.h:47:7: note:   candidate expects 1 argument, 0 provided

C:\Users\atulg\Desktop\Project\sketch_aug28a\sketch_aug28a.ino: In function 'void loop()':

sketch_aug28a:62:5: error: expected unqualified-id before '.' token

  DHT.read11(dht_dpin);

     ^

sketch_aug28a:66:25: error: expected primary-expression before '.' token

   lcd.print(humidity=DHT.humidity);

                         ^

sketch_aug28a:71:28: error: expected primary-expression before '.' token

   lcd.print(temperature=DHT.temperature);

                            ^

Multiple libraries were found for "DHT.h"
 Used: C:\Users\atulg\OneDrive\Documents\Arduino\libraries\DHT_sensor_library
 Not used: C:\Users\atulg\OneDrive\Documents\Arduino\libraries\arduino_710598
 Not used: C:\Users\atulg\OneDrive\Documents\Arduino\libraries\Grove_Temperature_And_Humidity_Sensor
 Not used: C:\Users\atulg\OneDrive\Documents\Arduino\libraries\DHT-sensor-library-master
Using library LiquidCrystal at version 1.0.7 in folder: C:\Program Files (x86)\Arduino\libraries\LiquidCrystal 
Using library DHT_sensor_library at version 1.3.7 in folder: C:\Users\atulg\OneDrive\Documents\Arduino\libraries\DHT_sensor_library 
Using library Adafruit_Sensor-master at version 1.0.3 in folder: C:\Users\atulg\OneDrive\Documents\Arduino\libraries\Adafruit_Sensor-master 
exit status 1
no matching function for call to 'DHT::DHT()'

**Comment by ladyada** [comment]
plesae contact your arduino seller for techsupport
