### ISSUE TITLE
Arduino library manager name is DHT sensor library instead of Adafruit DHT sensor library

### ISSUE THREAD

**Issue by dherrada** [adafruit/DHT-sensor-library#142]
I'm updating guides to instruct people to install libraries via the library manager instead of installing manually. For consistency's sake, I think it'd be good to rename the library (if possible) to Adafruit DHT sensor library

**Comment by ladyada** [comment]
yeah...thats not easily unfortunately, the library manager doesnt handle redirects and the name is the canonical identifier!
