### ISSUE TITLE
Add all functions like computeHeatIndex to DHT_Unified class

### ISSUE THREAD

**Issue by samuelcarreira** [adafruit/DHT-sensor-library#148]
Sorry if there is another way to call the `computeHeatIndex` function/method from the DHT_UNIFIED class (I am a C++ beginner), but if I use the DHT_U class, I can only use the Temperature and Humidity functions.
I've had to change the library and manually add the public method `float computeHeatIndex(bool isFahrenheit)` to the `DHT_U.h` file.
So my suggestion is to add the utility functions:

- convertCtoF()
- convertFtoC()
- computeHeatIndex()

to the DHT_U class.

Thank you

**Comment by caternuson** [comment]
The Unified Sensor version follows the Unified Sensor "standard":
https://learn.adafruit.com/using-the-adafruit-unified-sensor-driver/how-does-it-work
So "heat index" would need to be added there as a supported measured value.

It's not required to use the Unified version. Can use the non-Unified version for the additional features.
