### ISSUE TITLE
i need a help please, when i put to work this code this appear in IDH arduino:"Adafruit_Sensor.h: no such file or directory " what i can make ?

### ISSUE THREAD

**Issue by minahil188** [adafruit/DHT-sensor-library#163]
i need a help please, when i put to work this code this appear in IDH arduino:"Adafruit_Sensor.h: no such file or directory " How can I solve this issue?

**Comment by siddacious** [comment]
![image](https://user-images.githubusercontent.com/1183985/83912559-e8855400-a722-11ea-8752-82939efa915e.png)
