### ISSUE TITLE
error after 1.4.0 update

### ISSUE THREAD

**Issue by scottcowen** [adafruit/DHT-sensor-library#175]
tried to compile the "DHTtester" example code after 1.4.0 update using version 1.3.10 it would compile

In file included from /home/scott/Arduino/libraries/DHT_sensor_library/DHT.cpp:26:0:
/home/scott/Arduino/libraries/DHT_sensor_library/DHT.cpp: In constructor 'DHT::DHT(uint8_t, uint8_t, uint8_t)':
/home/scott/Arduino/libraries/DHT_sensor_library/DHT.h:56:46: error: 'SystemCoreClock' was not declared in this scope
 #define microsecondsToClockCycles(a) ((a) * (SystemCoreClock / 1000000L))
                                              ^
/home/scott/Arduino/libraries/DHT_sensor_library/DHT.cpp:51:7: note: in expansion of macro 'microsecondsToClockCycles'
       microsecondsToClockCycles(1000); // 1 millisecond timeout for
       ^~~~~~~~~~~~~~~~~~~~~~~~~
exit status 1
Error compiling for board Arduino Nano Every.

**Comment by ladyada** [comment]
duplicat eof https://github.com/adafruit/DHT-sensor-library/issues/172
