### ISSUE TITLE
Teensy 4.0 TeensySimultaneousADC.ino - dht11.h not found

### ISSUE THREAD

**Issue by pinaa** [adafruit/DHT-sensor-library#184]
This is an effort to port the TEENSY VERSION 3.1 MicroLoc to Teensy 4.0 but I'm failing miserably and I don't really know where I should be posting to.

I'm not troubleshooting per se and I could just delete the adafruit DHT code because my main focus is on just getting the code to run on the Teensy 4.0.

I am a retired electrical engineer with over 40 years of experience in the semiconductor industry, but I am quite stupid when it comes to some of this Arduino stuff, so I could call myself a "noob". My expertise is C/C++, Perl, and analog and digital circuit design with a lot of experience working with computer architects. My main problem is that I do not have a good understanding of the Arduino IDE even though I've been using it for over 8 years.

I'm running Ubuntu 20.04 and run a Windows 10 server whenever I need to run Windows applications or troubleshoot stuff, but I'm hoping someone can suggest what I might do to resolve this or direct me to the appropriate forum.

Thanks!
Ref:
ResolveLibrary(dht11.h)
In file included from /media/data/arduino-1.8.13/libraries/Adafruit_Circuit_Playground/utility/CP_Firmata.h:17:0,
  -> candidates: []
...
/media/data/arduino-1.8.13/libraries/Adafruit_Circuit_Playground/utility/CP_Boards.h:746:2: error: #error "Please edit CP_Boards.h with a hardware abstraction for this board"
 #error "Please edit CP_Boards.h with a hardware abstraction for this board"
  ^
/home/pinaar/wss/teensy31-micloc-master/TeensySimultaneousADC/TeensySimultaneousADC.ino:18:19: fatal error: dht11.h: No such file or directory
compilation terminated.
Using library EduIntro at version 0.0.12 in folder: /home/pinaar/Arduino/libraries/EduIntro
...
Using library ADC at version 8.0 in folder: /media/data/arduino-1.8.13/hardware/teensy/avr/libraries/ADC 
Error compiling for board Teensy 4.0.

**Comment by caternuson** [comment]
This error is for a different library:
```
/media/data/arduino-1.8.13/libraries/Adafruit_Circuit_Playground/utility/CP_Boards.h:746:2: error: #error "Please edit CP_Boards.h with a hardware abstraction for this board"
#error "Please edit CP_Boards.h with a hardware abstraction for this board"
^
```

This error is an incorrect import:
```
/home/pinaar/wss/teensy31-micloc-master/TeensySimultaneousADC/TeensySimultaneousADC.ino:18:19: fatal error: dht11.h: No such file or directory
```
There is no file `dht11.h` in this library. See example sketches.
