### ISSUE TITLE
DHT22 sensor failed to read values only after code upload

### ISSUE THREAD

**Issue by nikozila** [adafruit/DHT-sensor-library#194]
Hi there, How are you doing?

I have a weird problem with DHT22 sensor using DHT library last version along with the Nodemcu (esp8266).
The problem is: Only After code upload (using Serial or OTA) DHT sensor values are NAN (both for temperature and humidity). I must plug out and plugin in the power of nodemcu, Then DHT sensor would work fine.

Do you have any idea about it?
Thanks

**Comment by caternuson** [comment]
Can not recreate this behavior locally. Please post in the forums with details of your setup.
https://forums.adafruit.com/
