### ISSUE TITLE
`return` from inside `switch`-`case`

### ISSUE THREAD

**Issue by Mausy5043** [adafruit/DHT-sensor-library#30]
I noticed in the functions `readTemperature()` and `readHumidity()` that the result is returned from inside the case using `return f;`. So in one switch-case construct there are multiple `return`s. One for each case.

I was wondering if this is by design or not. I expected to see something like:
```
switch {
  case A:
    f = foo;
    break;
  case B:
    f = bar;
    break;
}
return f;
```

Is there some advantage to choose the current construct over the other?

**Comment by dhammika-marasinghe** [comment]
if we are returning value then we can't use break statement, but for other cases we need to add break statement to exits the switch.

**Comment by Mausy5043** [comment]
I tend to disagree.

**Comment by Mausy5043** [comment]
See PR #32 for what I mean.

**Comment by dhammika-marasinghe** [comment]
noted the problem. Thanks +1

**Comment by Mausy5043** [comment]
You're welcome. Have fun! :+1:

**Comment by Mausy5043** [comment]
I'm keeping this pull request open because it provides the functions with a single exit point which is IMHO more easily readable/understandable for beginners.
Up to @ladyada to decide completing the pul or not.

**Comment by dhammika-marasinghe** [comment]
yes it is. And you code looks stable. I think @ladyada will consider that.

**Comment by Mausy5043** [comment]
PR #33 should resolve this issue. Closing.
