### ISSUE TITLE
Problem during compilation in Arduino DUE board

### ISSUE THREAD

**Issue by CharlyBote** [adafruit/DHT-sensor-library#44]
![arduino](https://cloud.githubusercontent.com/assets/15068323/10413061/49708272-6f73-11e5-8cab-9adb18d1ccb3.png)
I receive this error when compile the test sketch.
C:\Users\charly\Documents\Arduino\libraries\DHT\DHT.cpp -o C:\Users\charly\AppData\Local\Temp\build5143615002772527901.tmp\DHT sensor library\DHT.cpp.o 
C:\Users\charly\Documents\Arduino\libraries\DHT\DHT.cpp: In constructor 'DHT::DHT(uint8_t, uint8_t, uint8_t)':
C:\Users\charly\Documents\Arduino\libraries\DHT\DHT.cpp:15:9: error: invalid conversion from 'Pio*' to 'uint8_t {aka unsigned char}' [-fpermissive]
   _port = digitalPinToPort(pin);
         ^
Error de compilación

Version of arduino 1.6.5
Board: DUE
Sensor: DHT22

**Comment by tdicola** [comment]
Oh ack, thanks for catching the issue!  Just took a look and realized it was a problem with the 8-bit AVR specific GPIO access code.  I put this behind an #ifdef that keeps it from being a problem on platforms like the Due.  Also gave it a quick test with a Due and it works great now.  Grab the latest version of the code (version 1.2.3) and it should be resolved, thanks!

**Comment by CharlyBote** [comment]
Thank you very much to respond.
I will probe this today.

Thanks again

best regards.

2015-10-13 1:33 GMT-03:00 Tony DiCola <notifications@github.com>:

> Oh ack, thanks for catching the issue! Just took a look and realized it
> was a problem with the 8-bit AVR specific GPIO access code. I put this
> behind an #ifdef that keeps it from being a problem on platforms like the
> Due. Also gave it a quick test with a Due and it works great now. Grab the
> latest version of the code (version 1.2.3) and it should be resolved,
> thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adafruit/DHT-sensor-library/issues/44#issuecomment-147599163>
> .
>



-- 
Carlos Botejara
IT Analyst
cbotejara@gmail.com
NEUQUEN - ARGENTINA
C: 0299-154230346
MSN:carlos.botejara@hotmail.com <carlos.botejara@hotmail.com>
*SKYPE: carlos.botejara*
LINKEDIN: http://www.linkedin.com/in/carlosbotejara

Este correo está dirigido únicamente a la persona o entidad que figura en
el destinatario y puede contener información confidencial y/o privilegiada.
La copia, reenvío, o distribución de este mensaje por personas o entidades
diferentes al destinatario está prohibido.
Si Ud. ha recibido este correo por error, por favor contáctese con el
remitente inmediatamente y borre el material de cualquier computadora.
Este correo puede estar siendo monitoreado en cumplimiento de esta política.
