### ISSUE TITLE
DHT Library 1.3.0 Does NOt Work

### ISSUE THREAD

**Issue by sghazagh** [adafruit/DHT-sensor-library#62]
Hi,
I can compile my project properly with DHT library 1.2.2.
However, after updating my library to version 1.3.0, this error raised and I cannot compile my project using DHT22 sensor:

//////////////////////////////////

```
C:\Users\xxxxxx\Documents\Arduino\libraries\DHT_sensor_library/DHT_U.h:25:29: fatal error: Adafruit_Sensor.h: No such file or directory

 #include <Adafruit_Sensor.h>

                             ^

compilation terminated.

exit status 1
Error compiling for board WeMos D1 R2 & mini.
```

/////////////////////////////

I cannot back to version 1.2.3 it says CRC error.
Backed to 1.2.2 and it compiles correctly.
Can you please advise!

**Comment by sghazagh** [comment]
I could manage to fix the compile issue by adding this :  https://github.com/adafruit/Adafruit_Sensor

But why we need it in first place and why cannot add it from Library Manager ???
(I manually added this to work)!!!!

**Comment by stelgenhof** [comment]
I am experiencing the same and adding `#include <Adafruit_Sensor.h>` does resolve the issue. It seems a requirement for the DHT Unified sensor, however I am using still the previous way (using DHT.h).

**Comment by oy5tein** [comment]
1.3.0 is broken here to (and adafruit sensors is not in library manager)
In DHT sensor lib in the lib manager I clicked on select version 1.2.3 and my old sketches started working again.

**Comment by sanjaybhagia** [comment]
I even tried version 1.2.3 (also with Adafruit_Sensor.h) but nothing seems to work for me. Its simply fails to read the data from the sensor.

**Comment by emilfihlman** [comment]
Broken here, too. Not cool pushing broken things to the public Arduino libraries...

**Comment by ViliusKraujutis** [comment]
I fixed this issue by saving [this Adafruit_Sensor.h file](https://github.com/adafruit/Adafruit_Sensor/blob/master/Adafruit_Sensor.h) to new folder `$ARDUINO_HOME$/libraries/Adafruit_Sensor/Adafruit_Sensor.h`.

**Comment by yusufbulentavci** [comment]
Including in this order solves the problem
#include <Adafruit_Sensor.h>
#include "DHT.h"_

**Comment by microbuilder** [comment]
You should be able to install the missing Adafruit_Sensor library from the Library Manager once you add the Adafruit .json file: 
<img width="398" alt="screen shot 2016-12-26 at 12 52 24" src="https://cloud.githubusercontent.com/assets/181073/21481640/5e14ebd8-cb6a-11e6-972e-c4b4efda6ad1.png">

**Comment by salmanfarisvp** [comment]
thanks @ViliusKraujutis. problem solved 
@microbuilder can you please add the .json link here...

**Comment by vijiarun** [comment]
please can anyone help me solving this??? I  too have the same error after downloading the library.

**Comment by vijiarun** [comment]
I am getting this error please help me to solve this error: 'dht' does not name a type
dht DHT;

**Comment by marcosavini** [comment]
Downgrading the lib to 1.2.3 worked for me.

**Comment by pucbaldwin** [comment]
Download the "Adafruit Unified Sensor" library from the library manager - this worked for me.

**Comment by JeremyOne** [comment]
I also had a problem with this, downgrading to 1.2.4 worked after I found this thread. It is a little distressing to do the automatic library upgrade in the Arduino IDE and suddenly have a broken compile.

**Comment by akeilox** [comment]
i had this exact same problem, and switching the DHT lib to 1.2.3 does solve the problem of compile error and compiles fine.

Didnt try the route of adding Adafruit Unified Sensor as suggested by others.

**Comment by rkveale** [comment]
As was previously mentioned, download the "Adafruit Unified Sensor" library from the library manager.
http://www.arduinolibraries.info/libraries/adafruit-unified-sensor

**Comment by chipytux** [comment]
Downgrade to 1.2.3 Version to solve your issue.

**Comment by jimgitonga** [comment]
Download the "Adafruit Unified Sensor" it worked out for me https://github.com/adafruit/Adafruit_Sensor

**Comment by chipytux** [comment]
Thank you, this work.
> Download the "Adafruit Unified Sensor" it worked out for me https://github.com/adafruit/Adafruit_Sensor

**Comment by hoegge** [comment]
But that library is not part of the Arduino IDE library manager, right? Which means a lot of people won't find it. Shouldn't it be included there as a part of the library using it?

**Comment by geofbaum** [comment]
@hoegge  I don't know which version of the IDE you might be using but I can see the Adafruit Unified Sensor in the library manager. It was the second to last one on the list that I got while filtering the search with 'Unified Sensor.'

**Comment by hoegge** [comment]
@geofbaum 1.8.5 - sorry tried again, now it is there. Must have made a typo or something - sorry for the inconvenience

**Comment by geofbaum** [comment]
@hoegge  No inconvenience at all! Glad you were able to find it!

**Comment by Gacon17** [comment]
Hi sghazagh,

I experienced the same problem, to remove that issue you should re-update the older version such as 1.2.3
It will work as your desire.

**Comment by salmanfarisvp** [comment]
For using [Adafruit DHT Humidity & Temperature](https://github.com/adafruit/DHT-sensor-library) library You must have the[ Adafruit Unified Sensor Library  ](https://github.com/adafruit/Adafruit_Sensor) in Arduino libraries.

**Comment by AgusTriwahyudin** [comment]
yes. you can downgrade to version 1.2.3

**Comment by Hammerschmidt** [comment]
You help me too. Thanks

**Comment by otmezger** [comment]
It sems that 1.3.1 still has the same problem. Downgrading to 1.2.3 works perfectly

**Comment by sachendra003** [comment]
Download the "Adafruit Unified Sensor" library from the library manager  - this worked for me.
![adafruit sensor header file_LI](https://user-images.githubusercontent.com/31585105/56715965-be5b1780-6756-11e9-9b3e-94223f95ce78.jpg)
