### ISSUE TITLE
dht11 library file issue

### ISSUE THREAD

**Issue by rishukumaragrahari** [adafruit/DHT-sensor-library#68]
Arduino: 1.8.0 Hourly Build 2016/12/21 04:34 (Windows 8.1), Board: "Arduino/Genuino Uno"

C:\Users\USER-1\AppData\Local\Temp\arduino_modified_sketch_878820\DHT_Unified_Sensor.ino:10:29: fatal error: Adafruit_Sensor.h: No such file or directory

 #include <Adafruit_Sensor.h>

                             ^

compilation terminated.

exit status 1
Error compiling for board Arduino/Genuino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by microbuilder** [comment]
You need to install the Adafruit_Sensor library as well: https://github.com/adafruit/Adafruit_Sensor

**Comment by rishukumaragrahari** [comment]
thanks

**Comment by rishukumaragrahari** [comment]
thanks
