### ISSUE TITLE
Include <Adafruit_Sensor.h> error

### ISSUE THREAD

**Issue by beguy** [adafruit/DHT-sensor-library#72]
Add [Adafruit_Sensor.h](https://github.com/adafruit/Adafruit_Sensor) in to the DHT sensor library. To avoid the issue of beginners.

**Comment by torabian** [comment]
I am having this issue. I've addded DHT but my build fails, since this file is not found. How can I do that?

**Comment by torabian** [comment]
I am trying to copy the file manually intodht sensor folder in my travis build hope to get results from there.

**Comment by idelara** [comment]
@torabian You have to manually copy and paste the file called "Adafruit_Sensor.h" from the repo @ViktorKovalev3 mentioned. Download (or clone) the repo, go to your Arduino library folder, locate the DHT library folder, and copy such file there.

**Comment by jimsy3** [comment]
i just installed somekind of Unified Sensors library(by adafruit) and then it worked for me

**Comment by rafagildin** [comment]
i need a help please, when i put to work this code this appear in IDH arduino:"Adafruit_Sensor.h: no such file or directory " what i can make ?

**Comment by Jotschi** [comment]
@rafagildin You need to download and install the https://github.com/adafruit/Adafruit_Sensor library as well.

**Comment by LRagji** [comment]
This is still a pain, not sure why was this closed Library management in arduino has not reached full potential of other package managers like npm where dependencies of dependencies are installed automatically for a new comer its still going to be a problem as the library is not available in library manager in arduino

**Comment by ladyada** [comment]
you can comment here to support Arduino's efforts
https://github.com/arduino/Arduino/pull/8600

**Comment by lekimtek** [comment]
Same problem in PlatfomIO, I resolved by copy this in sketch.ino;
#include <Adafruit_Sensor.h>
this resolve problem.
I dont now happens this, because  "#include <Adafruit_Sensor.h>" is in the library but not link wen compiling.
