### ISSUE TITLE
use more than one DHT sensor

### ISSUE THREAD

**Issue by notsolowki** [adafruit/DHT-sensor-library#77]
is it possible to connect 2 or more dht sensors at the same time to the same arduino?

**Comment by geofbaum** [comment]
The short answer is yes. Are you having an issue with running more than one sensor and if so what is the issue?

**Comment by geofbaum** [comment]
Also as a start I'd look at this post on the Arduino forum, there are two examples of code for running 2 or more sensors. 

http://forum.arduino.cc/index.php?topic=217689.0

**Comment by notsolowki** [comment]
thanks @geofbaum sorry i didnt research more before i asked this question.

**Comment by schel4ok** [comment]
Actually issue is not closed. There are many examples how to use few DHT sensors with DHT11Lib, but there is no example with Adafruit sensor library.
