### ISSUE TITLE
Fatal error: DHT.h: No such file or directory

### ISSUE THREAD

**Issue by FlorentSms** [adafruit/DHT-sensor-library#86]
Good evening,

Being a beginner in the arduino, I am currently experiencing a problem with my program. I try to read the data sent by a DHT11 type sensor.

I have correctly installed the library that you put online. I verified that it's in the Arduino libraries folder and I have checked that the Arduino IDE visualizes it well.

But when I try to upload the program, that's what he tells me:
https://puu.sh/xNwjj/e0bf912c99.png
https://puu.sh/xNwn6/1ad8fc18a3.png
https://puu.sh/xNwpB/23ace6dcb7.png

I think my library is well installed but I have the impression that it doesn't recognize it.
I hope you can help me.

Good night.

Florent

**Comment by geofbaum** [comment]
@FlorentSms  Can you delete the folder labeled DHT and download it through the Arduino IDE. The folder is not normally labeled just simply DHT as you show in your libraries folder. I don't think that's the issue but just to be on the safe side, I would remove the folder that you downloaded and said that you correctly installed. After you remove that folder go into Manage Libraries and search for DHT Sensor library and download it through the IDE. Try to upload it again to your Arduino after that is complete and report back if you are still having issues. The problem that you are having is normally related to something simple like it was not properly installed or that there are more than one copies of the DHT.h file floating around in your libraries folder.

Here is a picture of the Manage Libraries screen and the one you want to download to verify what you are after.
![arduino_dht](https://user-images.githubusercontent.com/9683836/31058249-a7928718-a6be-11e7-99bf-2eeec187a28b.png)

**Comment by geofbaum** [comment]
Also as an aside, you aren't using the same library as this one, you are using the SimpleDHT library so if my idea fixes your problem that is possibly a start. The SimpleDHT code is hosted at the following link I believe, https://github.com/winlinvip/SimpleDHT

**Comment by FlorentSms** [comment]
Hello @geofbaum ,
I have try your solutions but i have, for the 2 solutions, the same problem.

Thanks in advance.

Florent.

**Comment by geofbaum** [comment]
@FlorentSms Can you upload an image of what the files in your DHT library folder look like. I just want to check to make sure capitalization or if somehow the files are misnamed somehow.

**Comment by FlorentSms** [comment]
@geofbaum 
Yes no problem:
https://puu.sh/xPbas/82a0051685.png
https://puu.sh/xPbbC/2a5873b271.png

**Comment by SuriGangs** [comment]
Hi, could you solve your problem?

**Comment by JackZ0** [comment]
\Adafruit_AM2320_sensor_library/Adafruit_AM2320.h:41:29: fatal error: Adafruit_Sensor.h: No such file or directory

**Comment by isekaimaou1109** [comment]
> @FlorentSms Can you delete the folder labeled DHT and download it through the Arduino IDE. The folder is not normally labeled just simply DHT as you show in your libraries folder. I don't think that's the issue but just to be on the safe side, I would remove the folder that you downloaded and said that you correctly installed. After you remove that folder go into Manage Libraries and search for DHT Sensor library and download it through the IDE. Try to upload it again to your Arduino after that is complete and report back if you are still having issues. The problem that you are having is normally related to something simple like it was not properly installed or that there are more than one copies of the DHT.h file floating around in your libraries folder.
> 
> Here is a picture of the Manage Libraries screen and the one you want to download to verify what you are after.
> ![arduino_dht](https://user-images.githubusercontent.com/9683836/31058249-a7928718-a6be-11e7-99bf-2eeec187a28b.png)

yeah i see and when i do it as you said, i also get the same error
delete DHT folder in libraries then install it via Arduino IDE and still get that error and don't have any file DHT.h floating around my sketch
help me please, graceful and tks so much <3

**Comment by Diohicham** [comment]
Arduino: 1.8.13 (Windows Store 1.8.42.0) (Windows 10), Board: "Arduino Uno"

sketch_nov10a:1:10: fatal error: dht.h: No such file or directory

 #include "dht.h"

          ^~~~~~~

compilation terminated.

exit status 1

dht.h: No such file or directory



This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by ZsoZ** [comment]
#include <DHT.h>

**Comment by Arely-M** [comment]
Puede ser porque falta una librería  Adafruit Unified Sensor, esta viene al instalar todo desde el administrador de bibliotecas
![libreria](https://user-images.githubusercontent.com/64564747/174499834-c62a7040-72d6-4bac-83fc-2c5bac6e9f05.png)

**Comment by hernandez2david** [comment]
> Puede ser porque falta una librería Adafruit Unified Sensor, esta viene al instalar todo desde el administrador de bibliotecas
You Rock Arely! This worked

**Comment by selenium78965** [comment]
It's working!!Thanks

> Puede ser porque falta una librería Adafruit Unified Sensor, esta viene al instalar todo desde el administrador de bibliotecas ![libreria](https://user-images.githubusercontent.com/64564747/174499834-c62a7040-72d6-4bac-83fc-2c5bac6e9f05.png)

**Comment by TennisTerror** [comment]
For anyone who still struggle with this, it can be that your directory included non english letters
