### ISSUE TITLE
Fluctuating load cell reading with HX711

### ISSUE THREAD

**Issue by Koktung** [adafruit/DHT-sensor-library#88]
Hi guy, currently I doing a load cell measuring the compression force project. I had connected the load cell with an ADC amplifying module (HX711) to Arduino mega 2560. I connected between the load cell with the HX711 module as below:
 1. Load cell Red (Excitation voltage +) to HX711 (E + port)
 2. Load cell Black (Excitation voltage -) to HX711 (E - port)
 3. Load cell White (Excitation voltage -) to HX711 (A - port)
 4. Load cell Green (Excitation voltage +) to HX711 (A + port)

Connection between the HX711 with Arduino Mega 2560 as below:
 1. HX711 GND  to Arduino GND 
 2. HX711 DT  to Arduino 3
 3. HX711 SCK  to Arduino 2
 4. HX711 VCC  to Arduino 5V

I used the calibration code for the load cell and its library from [https://learn.sparkfun.com/tutorials/load-cell-amplifier-hx711-breakout-hookup-guide]

Below is the Arduino’s calibration code that I used.
`
#include "HX711.h"

#define DOUT  3
#define CLK  2

HX711 scale(DOUT, CLK);

float calibration_factor = -7050; //-7050 worked for my 440lb max scale setup

void setup() {
  Serial.begin(9600);
  Serial.println("HX711 calibration sketch");
  Serial.println("Remove all weight from scale");
  Serial.println("After readings begin, place known weight on scale");
  Serial.println("Press + or a to increase calibration factor");
  Serial.println("Press - or z to decrease calibration factor");

  scale.set_scale();
  scale.tare(); //Reset the scale to 0

  long zero_factor = scale.read_average(); //Get a baseline reading
  Serial.print("Zero factor: "); //This can be used to remove the need to tare the scale. Useful in permanent scale projects.
  Serial.println(zero_factor);
}

void loop() {

  scale.set_scale(calibration_factor); //Adjust to this calibration factor

  Serial.print("Reading: ");
  Serial.print(scale.get_units(), 1);
  Serial.print(" lbs"); //Change this to kg and re-adjust the calibration factor if you follow SI units like a sane person
  Serial.print(" calibration_factor: ");
  Serial.print(calibration_factor);
  Serial.println();

  if(Serial.available())
  {
    char temp = Serial.read();
    if(temp == '+' || temp == 'a')
      calibration_factor += 10;
    else if(temp == '-' || temp == 'z')
      calibration_factor -= 10;
  }
}
`

**Comment by JOSEPH12312** [comment]
HELLO ... please .. i have this flutuation in hx711 load cell and arduino.. how did you solve urs? was it h/w ? should i buy another load cell or hx711 or both or... etc ? please answer me at hellojoseph1@yahoo.com
