### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by TheGreyDiamond** [adafruit/DHT-sensor-library#90]
If I try to compile the example code the following Error appears:
` C:\Users\*****\AppData\Local\Temp\arduino_modified_sketch_414522\DHT_Unified_Sensor.ino:10:29: fatal error: Adafruit_Sensor.h: No such file or directory`
 `#include <Adafruit_Sensor.h>`

                             ^

`compilation terminated.`

 `exit status 1`

**Comment by ludwhe** [comment]
Did you download and install the Adafruit Sensor library @ https://github.com/adafruit/Adafruit_Sensor?
